name: custom_floating_navigation_bar
description: A beautiful and highly customizable floating navigation bar for Flutter with smooth animations, badge support, and multiple styles.
version: 1.0.2 # पहला stable version – 0.0.1 बहुत पुराना है
homepage: https://github.com/pks050505/floating_navigation_bar
repository: https://github.com/pks050505/floating_navigation_bar

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Optional but recommended – बेहतर दिखता है pub.dev पर
topics:
  - navigation-bar
  - floating-navigation
  - bottom-navigation
  - flutter-ui
  - widgets

flutter:
